[project]
name = "m2_dm3"
r_version = "4.6"

repositories = [
    {alias = "CRAN", url = "https://packagemanager.posit.co/cran/latest"},
]

dependencies = [
    { name = "hebstr", git = "https://github.com/hebstr/hebstr", branch = "main" },
    "tidyverse",
    "tidymodels",
    "mice",
    "labelled",
    "gtsummary",
    "MatchIt",
    "halfmoon",
    "ggsurvfit",
    "sessioninfo",
]
